apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.example.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-ingress.yaml
  - networkpolicy-allow-egress.yaml
  - logging/fluent-bit-configmap.yaml
