apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sustainability-roi-allow-ingress
  namespace: sustainability-roi
spec:
  podSelector:
    matchLabels:
      app: sustainability-roi
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sustainability-roi
      ports:
        - protocol: TCP
          port: 8501
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9108
