apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sustainability-roi-data
  namespace: sustainability-roi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
